spring:
   application:
      name: StoreChain-Server
   sleuth:
      async:
         enabled: false
   cloud:
      refresh:
         enabled: false
      compatibility-verifier:
         enabled: false
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:@db-port@/@db-database@
      username: "@db-user@"
      password: "@db-password@"
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: false
   redis:
      database: 1
      host: "@redis-host@"
      port: 0@redis-port@
      password: "@redis-password@"
      timeout: 300ms
logging:
   file: 
      name: ./logs/spring.log
   level:
      root: INFO

server:
   port: "@tomcat-port@"
   ssl:
      enable: true
      key-store: classpath:keystore/storechain.p12
      key-store-password: 123456
      key-store-type: PKCS12
      key-alias: storechain
eureka:
   instance:
      hostname: localhost
   client:
      registerWithEureka: false
      fetchRegistry: false
      service-url:
         defaultZone: https://localhost:@tomcat-port@/eureka
netty:
   enable: true
   servers:
      -
         name: web-socket
         port: "@websocket-port@"
         provider: com.storechain.spring.boot.connection.netty.WebSocketServerProvider
         handler: com.storechain.connection.netty.websocket.handler.WebSocketServerInitializeHandler
         client-converter: com.storechain.connection.netty.websocket.WebSocketClientConverter
         options:
            -
               SO_BACKLOG: 1024
         encode-endian: BIG
         decode-endian: BIG
         charset: UTF-8
         log-user-active: true
         log-user-inactive: true
         log-channel-read: true
         log-channel-write: true
         kick-unknown-packet-user: true
         log-banned-ip-active: true
system:
   task-provider:
      thread-count: 16
      maxThreadCount: -1
      keep-alive-minutes: 5
      allow-core-thread-timeout: true
      remove-on-cancel-policy: true
      continue-existing-periodic-tasks-after-shutdown-policy: false
      execute-existing-delayed-tasks-after-shutdown-policy: false
