# This is a basic workflow to help you get started with Actions
# https://gist.github.com/linux-china/8745394fbc308168b20068386771ea1b
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  linux-build-jvm:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '8.0'
      - run: ln -s /usr/lib64/libtinfo.so.6.1 /usr/lib64/libtinfo.so.5
      - run: mysql -uroot -hlocalhost -uroot -e 'CREATE DATABASE testdb;'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.8.2
      - run: java --version
      - run: mysql -V
      - run: mvn --version
      - name: Build with Maven
        run: mvn -DskipTests -B clean package
      - name: Run App
        run: java -jar target/storechain-server.jar
  linux-build-docker:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.8.2
      - run: java --version
      - run: docker --version
      - run: docker-compose --version
      - run: mvn --version
      - name: Build with Maven
        run: mvn -DskipTests -B clean package -Pdocker
      - run: docker images
      - name: Run App
        run: docker start storechain-server
  linux-build-native:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: 17
          graalvm-version: 21.3.0
          native-image: true
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.8.2
      - uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '8.0'
      - run: ln -s /usr/lib64/libtinfo.so.6.1 /usr/lib64/libtinfo.so.5
      - run: mysql -uroot -hlocalhost -uroot -e 'CREATE DATABASE testdb;'
      - run: java --version
      - run: native-image --version
      - run: mysql -V
      - run: mvn --version
      - name: Build with Maven
        run: mvn -DskipTests -B clean package -Pnative
      - name: Run App
        run: target/storechain-server

      
