# This is a basic workflow to help you get started with Actions
# https://gist.github.com/linux-china/8745394fbc308168b20068386771ea1b
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch.
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  macos-native:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: 17
          graalvm-version: 22.1.0
          native-image: true
      - run: gu install python
      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.8.2
      - name: Setup Redis
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: 'latest'
          redis-port: 6379
      - run: redis-cli -h 127.0.0.1 -p 6379 ping
      - name: Setup MySQL
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '8.0'
          root-password: hT9zS5cR8aY4vM3r
      - run: mysql -uroot -phT9zS5cR8aY4vM3r -h127.0.0.1 -e 'CREATE DATABASE testdb'
      - run: java --version
      - run: native-image --version
      - run: mvn --version
      - name: Build with Maven
        run: mvn -DskipTests=false -Ddb-password=hT9zS5cR8aY4vM3r clean package -Pnative
  linux-build-jvm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: 17
          graalvm-version: 22.1.0
          native-image: false
      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.8.2
      - name: Setup Redis
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: 'latest'
      - name: Setup MySQL
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '8.0'
          root-password: hT9zS5cR8aY4vM3r
      - run: mysql -uroot -phT9zS5cR8aY4vM3r -h127.0.0.1 -e 'CREATE DATABASE testdb'
      - run: java --version
      - run: mvn --version
      - name: Build with Maven
        run: mvn -DskipTests=false -Ddb-password=hT9zS5cR8aY4vM3r clean package
  linux-build-docker-native:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.8.2
      - run: java --version
      - run: docker --version
      - run: docker-compose --version
      - run: mvn --version
      - name: Build with Maven
        run: mvn -B -Dredis-host=redis -Ddb-host=db clean install -Pdocker -Ddocker-target=native
      - run: docker images
      - run: docker image prune -f
      - run: docker rm -f cobnet-redis cobnet-db cobnet
  linux-build-docker-jvm:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.8.2
      - run: java --version
      - run: docker --version
      - run: docker-compose --version
      - run: mvn --version
      - name: Build with Maven
        run: mvn -B -Dredis-host=redis -Ddb-host=db clean install -Pdocker -Ddocker-target=jvm
      - run: docker images
      - run: docker image prune -f
      - run: docker rm -f cobnet-redis cobnet-db cobnet
  linux-build-native:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: 17
          graalvm-version: 22.1.0
          native-image: true
      - run: gu install python
      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.8.2
      - name: Setup Redis
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: 'latest'
      - run: sudo apt install libncurses5 -y
      - name: Setup MySQL
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '8.0'
          root-password: hT9zS5cR8aY4vM3r
      - run: mysql -uroot -phT9zS5cR8aY4vM3r -h127.0.0.1 -e 'CREATE DATABASE testdb'
      - run: java --version
      - run: native-image --version
      - run: mvn --version
      - name: Build with Maven
        run: mvn -DskipTests=false -Ddb-password=hT9zS5cR8aY4vM3r clean package -Pnative test