# This is a basic workflow to help you get started with Actions
# https://gist.github.com/linux-china/8745394fbc308168b20068386771ea1b
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  linux-build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: 17
          graalvm-version: 21.3.0
          native-image: true
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.8.2
      - run: java --version
      - run: apt-get upgrade docker
      - run: apt-get upgrade docker-compose
      - run: docker --version
      - run: docker-compose --version
      - name: Build with Maven
        run: mvn -DskipTests -B clean package -Pdocker
      - name: Run App
        run: docker start storechain-server
      
